//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobasa.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string QueueServerHost {
            get {
                return ((string)(this["QueueServerHost"]));
            }
            set {
                this["QueueServerHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public int QueueServerPort {
            get {
                return ((int)(this["QueueServerPort"]));
            }
            set {
                this["QueueServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CALL#1")]
        public string StationName {
            get {
                return ((string)(this["StationName"]));
            }
            set {
                this["StationName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST0")]
        public string StationPost {
            get {
                return ((string)(this["StationPost"]));
            }
            set {
                this["StationPost"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C4BC3A3AC2D6D367A74580388B20BC069C96B048DFEAF5CCDC0CE1E25BF23F39")]
        public string SecuritySalt {
            get {
                return ((string)(this["SecuritySalt"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tobasaqueue")]
        public string QueueUserName {
            get {
                return ((string)(this["QueueUserName"]));
            }
            set {
                this["QueueUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("e4ee0e54215f5e3dd7683923abe1dac8")]
        public string QueuePassword {
            get {
                return ((string)(this["QueuePassword"]));
            }
            set {
                this["QueuePassword"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>POST0|Poli Gigi</string>
  <string>POST1|Poli Mata</string>
  <string>POST2|Poli Kandungan</string>
  <string>POST3|Poli Bedah</string>
  <string>POST4|Poli Anak</string>
  <string>POST5|Poli Ortopedi</string>
  <string>POST6|Poli Jantung</string>
  <string>POST7|Poli THT</string>
  <string>POST8|Poli Kulit</string>
  <string>POST9|Poli Dalam</string>
  <string>POST10|Poli Saraf</string>
  <string>POST11|Poli Psikiatri</string>
  <string>POST12|Poli Paru</string>
  <string>POST13|Rehab Medik</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UIPostList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UIPostList"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ManageAllPostAdvanceQueue {
            get {
                return ((bool)(this["ManageAllPostAdvanceQueue"]));
            }
            set {
                this["ManageAllPostAdvanceQueue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ManageAdvanceQueue {
            get {
                return ((bool)(this["ManageAdvanceQueue"]));
            }
            set {
                this["ManageAdvanceQueue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowPostsButtonDiv {
            get {
                return ((bool)(this["ShowPostsButtonDiv"]));
            }
            set {
                this["ShowPostsButtonDiv"] = value;
            }
        }
    }
}
